version: '3'

services:
  app-dev:
    image: 'app-base-mongo'
    container_name: 'app-base-mongo'
    command: nest start --debug 0.0.0.0:9229 --watch
    volumes:
      - .:/usr/src/app
    ports:
      - 3030:3001
      - 9220:9229
    restart: on-failure
    env_file:
      - .env
    networks:
      - app-base-mongo-network

  mongo:
    image: mongo
    container_name: mongo-app-base
    restart: on-failure
    networks:
      - app-base-mongo-network
    volumes:
      - app-base-mongo:/data
    ports:
      - 27023:27017

volumes:
  app-base-mongo:

networks:
  app-base-mongo-network:
